permissions:
  pull-requests: write
  
name: Auto Close PRs Immediately

on:
  pull_request:
    types: [opened]

jobs:
  auto-close:
    runs-on: ubuntu-latest
    steps:
      - name: Close PR and leave comment
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const prNumber = pr.number;
            const prAuthor = pr.user.login;

            // Leave a comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `This pull request has been automatically closed because PRs are not used in this repository, please open a issue instead.`
            });

            // Close the PR
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              state: 'closed'
            });
