name: Issue Auto-Responder

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Post comment on new issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "Thanks for opening this issue! We'll get back to you within a week or three. Stay tuned!"
            })
