name: Comment on "Unable to Reproduce" Label

on:
  issue:
    types:
      - labeled

permissions:
  issues: write

jobs:
  comment-on-unable-to-reproduce:
    if: ${{ github.event.label.name == 'status: unable to reproduce' }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: github.context.payload.issue.number,
              body: "⚠️ We were unable to reproduce the bug as described. Unless more details are provided to help us replicate the issue, it may be dismissed. Please update the issue with any additional information you can share."
            })
